export const USER_PREFERRED_ADDRESS_ENTERED = 'USER_PREFERRED_ADDRESS_ENTERED';
export const USER_PREFERRED_ADDRESS_ERROR = 'USER_PREFERRED_ADDRESS_ERROR';
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
