export { default as logo } from "../static/images/logo.png";
export { default as pattern } from "../static/images/pattern.png";
export { default as heart } from "../static/images/heart.svg";
export { default as home } from "../static/images/home.svg";
export { default as list } from "../static/images/list.svg";
export { default as man } from "../static/images/man.svg";
export { default as shop } from "../static/images/shop.svg";
export { default as hamburger } from "../static/images/hamburger.svg";
export { default as cart } from "../static/images/cart.svg";
export { default as slider_books } from "../static/images/slider_books.jpg";
export { default as slider_fastfood } from "../static/images/slider_fastfood.jpg";
export { default as slider_groceries } from "../static/images/slider_groceries.jpg";
export { default as slider_rawfoods } from "../static/images/slider_rawfoods.jpg";
export { default as Layout } from "../components/layout";
export {default as Footer} from "../components/footer";
export {default as Header} from "../components/header";
export {default as HomepageSlider} from "../components/slider";